pagina/urls.py
from django.urls import path
from . import views
from .views import exit

from django.conf import settings
from django.contrib.staticfiles.urls import static

urlpatterns = [
    path('', views.inicio, name='inicio'),
    path('logout/', exit, name='exit'),
    path('nosotros', views.nosotros, name='nosotros'),
    path('servicios', views.servicios, name='servicios'),
    path('contacto', views.contacto, name='contacto'),
    path('presupuesto', views.presupuesto, name='presupuesto'),
    path('add_to_budget/<int:material_id>/', views.add_to_budget, name='add_to_budget'),
    path('remove_from_budget_presupuesto/<int:material_id>/', views.remove_from_budget_presupuesto, name='remove_from_budget_presupuesto'),
    path('factura', views.factura, name='factura'),
    path('add_to_budget_factura/<int:material_id>/', views.add_to_budget_factura, name='add_to_budget_factura'),
    path('remove_from_budget/<int:material_id>/', views.remove_from_budget, name='remove_from_budget'),
    path('materiales', views.materiales, name='materiales'),
    path('materiales/crear', views.crear, name='crear'),
    path('materiales/editar', views.editar, name='editar'),
    path('materiales/editar/<int:id>', views.editar, name='editar'),
    path('eliminar/<int:id>', views.eliminar, name='eliminar'),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sistema/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pagina.urls')), 
    path('accounts/', include('django.contrib.auth.urls')),
]

pagina/models.py
from django.db import models

# Create your models here.
class Material(models.Model):
    id = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=100, verbose_name='Nombre')
    CHOICES = [
        ('option1', 'Metro Cuadrado'),
        ('option2', 'Metro Cubico'),
        ('option3', 'Kilo'),
        ('option4', 'Unidad'),
    ]
    medida = models.CharField(max_length=20, choices=CHOICES, verbose_name='Medida')
    precio = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Precio')
    descripcion = models.CharField(max_length=100, verbose_name='Descripcion')
    imagen = models.ImageField(upload_to='img/uploads', null=True, verbose_name='Imagen')

    def __str__(self):
        fila = "Nombre: " + self.nombre
        return fila

    def delete(self, using=None, keep_parents=False):
        self.imagen.storage.delete(self.imagen.name)
        super().delete()

class Cart(models.Model):
    id = models.AutoField(primary_key=True)
    session_key = models.CharField(max_length=255, unique=True)
    materials = models.ManyToManyField(Material, through='CartMaterial')

class CartMaterial(models.Model):
    id = models.AutoField(primary_key=True)
    material = models.ForeignKey(Material, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)

pagina/forms.py
from django import forms
from .models import Material

class MaterialForm(forms.ModelForm):
    class Meta:
        model = Material
        fields = '__all__'

class MaterialSearchForm(forms.Form):
    search_term = forms.CharField(max_length=100, required=False)

pagina/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from .models import Material, Cart, CartMaterial
from .forms import MaterialForm, MaterialSearchForm
# Create your views here.

def inicio(request):
    return render(request, 'paginas/index.html')

def nosotros(request):
    return render(request, 'paginas/nosotros.html')

def servicios(request):
    return render(request, 'paginas/servicios.html')

def contacto(request):
    return render(request, 'paginas/contacto.html')

def presupuesto(request):
    material = Material.objects.all()
    session_key = request.session.session_key
    if not session_key:
        request.session.create()
        session_key = request.session.session_key
    try:
        cart = Cart.objects.get(session_key=session_key)
    except Cart.DoesNotExist:
        cart = Cart.objects.create(session_key=session_key)

    cart_material = CartMaterial.objects.filter(cart=cart)

    return render(request, 'paginas/presupuesto.html', {'material': material, 'cart_material': cart_material})

def add_to_budget(request, material_id):
    material = get_object_or_404(Material, pk=material_id)
    session_key = request.session.session_key

    if not session_key:
        request.session.create()
        session_key = request.session.session_key

    cart, created = Cart.objects.get_or_create(session_key=session_key)

    try: 
        cart_material = CartMaterial.objects.get(cart=cart, material=material)
        cart_material.quantity += 1
        cart_material.save()
    except CartMaterial.DoesNotExist:
        CartMaterial.objects.create(cart=cart, material=material, quantity=1)

    return redirect('presupuesto')

def remove_from_budget_presupuesto(request, material_id):
    material = get_object_or_404(Material, pk=material_id)
    session_key = request.session.session_key

    cart = Cart.objects.get(session_key=session_key)

    try:
        cart_material = CartMaterial.objects.get(cart=cart, material=material)
        if cart_material.quantity > 1:
            cart_material.quantity -= 1
            cart_material.save()
        else:
            cart_material.delete()
    except CartMaterial.DoesNotExist:
        pass

    return redirect('presupuesto')

def factura(request):
    session_key = request.session.session_key
    if not session_key:
        request.session.create()
        session_key = request.session.session_key
    try:
        cart = Cart.objects.get(session_key=session_key)
    except Cart.DoesNotExist:
        cart = Cart.objects.create(session_key=session_key)

    cart_material = CartMaterial.objects.filter(cart=cart)
    total = sum(item.material.precio * item.quantity for item in cart_material)

    return render(request, 'paginas/factura.html', {'cart_material': cart_material, 'total': total})

def add_to_budget_factura(request, material_id):
    material = get_object_or_404(Material, pk=material_id)
    session_key = request.session.session_key

    if not session_key:
        request.session.create()
        session_key = request.session.session_key

    cart, created = Cart.objects.get_or_create(session_key=session_key)

    try: 
        cart_material = CartMaterial.objects.get(cart=cart, material=material)
        cart_material.quantity += 1
        cart_material.save()
    except CartMaterial.DoesNotExist:
        CartMaterial.objects.create(cart=cart, material=material, quantity=1)

    return redirect('factura')    

def remove_from_budget(request, material_id):
    material = get_object_or_404(Material, pk=material_id)
    session_key = request.session.session_key

    cart = Cart.objects.get(session_key=session_key)

    try:
        cart_material = CartMaterial.objects.get(cart=cart, material=material)
        if cart_material.quantity > 1:
            cart_material.quantity -= 1
            cart_material.save()
        else:
            cart_material.delete()
    except CartMaterial.DoesNotExist:
        pass

    return redirect('factura')

@login_required
def materiales(request):
    materiales = Material.objects.all()
    form = MaterialSearchForm(request.GET)

    if form.is_valid():
        search_term = form.cleaned_data['search_term']
        if search_term:
            materiales = materiales.filter(nombre__icontains=search_term)

    return render(request, 'materiales/index.html', {'materiales': materiales, 'form': form})
@login_required
def crear(request):
    formulario = MaterialForm(request.POST or None, request.FILES or None)
    if formulario.is_valid():
        formulario.save()
        return redirect('materiales')
    return render(request, 'materiales/crear.html', {'formulario': formulario})
@login_required
def editar(request, id):
    material = Material.objects.get(id=id)
    formulario = MaterialForm(request.POST or None, request.FILES or None, instance=material)
    if formulario.is_valid() and request.method == 'POST':
        formulario.save()
        return redirect('materiales')
    return render(request, 'materiales/editar.html', {'formulario': formulario})
@login_required
def eliminar(request, id):
    material = Material.objects.get(id=id)
    material.delete()
    return redirect('materiales')

def exit(request):
    logout(request)
    return redirect('inicio')

pagina/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <title> {% block titulo %} {% endblock %} </title>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS v5.2.1 -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
  <link rel="stylesheet" href="/img/css/base.css">

  <link rel="icon" type="image/x-icon" href="/img/img/cepsa icono.png">

</head>

<body>
    
  <header>
    <!-- place navbar here -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand mx-auto" href="#">
        <img src="/img/img/cepsa logo sin texto.png" alt="Logo" height="100">
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav mx-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'inicio' %}">Inicio</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'servicios' %}">Servicios</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'contacto' %}">Contacto</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'nosotros' %}">Nosotros</a>
          </li>
          {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'exit' %}">Salir</a>
          </li>
          {% endif %}
        </ul>
        
      </div>
    </nav>

  </header>
  <main>

                {% block contenido %} {% endblock %}

  </main>

    <!-- place footer here -->
      <footer class="text-white text-center text-lg-start bg-dark">
        <!-- Grid container -->
        <div class="container p-4">
          <!--Grid row-->
          <div class="row mt-4">
            <!--Grid column-->
            <div class="col-md-4">
              <h5 class="text-uppercase mb-4">REDES</h5>
    
              <p>
                © CEPSA
              </p>
    
              <div class="mt-4">
                <!-- Facebook -->
                <a type="button" class="btn btn-floating btn-light btn-lg"><i class="fab fa-facebook-f"></i></a>
                <!-- Twitter -->
                <a type="button" class="btn btn-floating btn-light btn-lg"><i class="fab fa-twitter"></i></a>
                <!-- WhatsApp -->
                <a type="button" class="btn btn-floating btn-light btn-lg"><i class="fab fa-whatsapp"></i></a>

              </div>
            </div>
            <!--Grid column-->
    
            <!--Grid column-->
            <div class="col-md-4">
              <h5 class="text-uppercase mb-4">Información</h5>
              <ul class="fa-ul">
                <li class="mb-3">
                  <span class="fa-li"><i class="fas fa-home"></i></span><span class="ms-2">Dirección</span>
                </li>
                <li class="mb-3">
                  <span class="fa-li"><i class="fas fa-envelope"></i></span><span class="ms-2">correo@example.com</span>
                </li>
                <li class="mb-3">
                  <span class="fa-li"><i class="fas fa-phone"></i></span><span class="ms-2">Número de contacto</span>
                </li>
              </ul>
            </div>
            <!--Grid column-->
    
            <!--Grid column-->
            <div class="col-md-4">
              <h5 class="text-uppercase mb-4">Links</h5>
    
              <table class="table text-white">
                <tbody class="fw-normal">
                  <tr>
                    <td>Preguntas Frecuentes</td>
                  </tr>
                  <tr>
                    <td>Precios</td>
                  </tr>
                  <tr>
                    <td>Información</td>
                  </tr>
                </tbody>
              </table>
            </div>
            <!--Grid column-->
          </div>
          <!--Grid row-->
        </div>
        <!-- Grid container -->
    
        <!-- Copyright -->
        <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
          © 2020 Copyright:
          <a class="text-white" href="https://mdbootstrap.com/">MDBootstrap.com</a>
        </div>
        <!-- Copyright -->
      </footer>
  <!-- Bootstrap JavaScript Libraries -->
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
    integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous">
  </script>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.min.js"
    integrity="sha384-7VPbUDkoPSGFnVtYi0QogXtr74QeVeeIs99Qfg5YCF+TidwNdjvaKZX19NZ/e6oz" crossorigin="anonymous">
  </script>
</body>

</html>

pagina/templates/materiales/crear.html
{% extends "base.html" %}

{% block titulo %} Agregar Materiales {% endblock %}

{% block contenido %} 

<div class="card">
    <div class="card-header">
        Añadir Material 
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-md-4">
                <h4 class="card-title">Datos</h4>
                {% include 'materiales/form.html'%}
            </div>
            <div class="col-md-4">
                <img src="/img/img/materiales.png" alt="materiales">
            </div>
        </div>   
    </div>

   
    <div class="card-footer text-muted">

    </div>
</div>

{% endblock %}

pagina/templates/materiales/editar.html
{% extends "base.html" %}

{% block titulo %} Editar Materiales
{% endblock %}

{% block contenido %} 

<div class="card">
    <div class="card-header">
        Editar Material 
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-md-4">
                <h4 class="card-title">Datos</h4>
                {% include 'materiales/form.html'%}
            </div>
            <div class="col-md-4">
                <img src="/img/img/materiales.png" alt="materiales">
            </div>
        </div>   
    </div>

   
    <div class="card-footer text-muted">

    </div>
</div>

{% endblock %}

pagina/templates/materiales/form.html
<form enctype="multipart/form-data" method="post">
    {% csrf_token %}
    {{ formulario.as_p }}
    <button class="btn btn-primary" type="submit">Submit</button>
</form>

pagina/templates/materiales/index.html
{% extends "base.html" %}

{% block titulo %} Lista Materiales {% endblock %}

{% block contenido %} 

<div class="card">
    <div class="card-header">
       <a name="" id="" class="btn btn-success" href="{% url 'crear' %}" role="button">Agregar Materiales</a>
    </div>
    <div class="card-body">
        <h4 class="card-title">Materiales</h4>
        <div class="input-group">
            <div class="form-outline">
                <form method="get" action="{% url 'materiales' %}">
                    <input type="text" class="form-control" name="search_term" placeholder="Nombre" maxlength="100" id="id_search_term">
            </div>
                    <button type="submit" class="btn btn-info">Buscar</button>
                </form>
        </div>
        <div class="table-responsive">
            <table class="table table-secondary">
                <thead>
                    <tr>
                        <th scope="col">Imagen</th>
                        <th scope="col">ID</th>
                        <th scope="col">Nombre</th>
                        <th scope="col">Medida</th>
                        <th scope="col">Precio</th>
                        <th scope="col">Descripción</th>
                        <th scope="col">Acciones</th>

                    </tr>
                </thead>
                <tbody>

                    {% for material in materiales %}
                    <tr class="">
                        <td>
                            <img src="{{ material.imagen.url }}" height="50">
                        </td>
                        <td scope="row">{{ material.id }}</td>
                        <td>{{ material.nombre }}</td>
                        <td>{{ material.get_medida_display }}</td>
                        <td>{{ material.precio }}</td>
                        <td>{{ material.descripcion }}</td>
                        
                        <td>
                            <a name="" id="" class="btn btn-info" href="{% url 'editar' material.id %}" role="button">Editar</a>
                            |
                            <a name="" id="" class="btn btn-danger" href="{% url 'eliminar' material.id %}" role="button">Borrar</a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        
    </div>
</div>

{% endblock %}

pagina/templates/paginas/contacto.html
{% extends "base.html" %}

{% block titulo %} Contacto {% endblock %}

{% block contenido %}
<div class="container mt-5">
    <div class="card">
        <div class="card-body">
            <div class="text-center">
                <h2>¡Escribenos tus dudas!</h2>
            </div>
            <form action="#" method="post" id="contactForm">
                <!-- Email Field -->
                <div class="form-group">
                    <label for="inputEmail">Correo electronico</label>
                    <input type="email" class="form-control" id="inputEmail" name="email" placeholder="ejemplo@gmail.com" required>
                </div>
        
                <!-- Message Field -->
                <div class="form-group">
                    <label for="inputMessage">Mensaje</label>
                    <textarea class="form-control" id="inputMessage" name="message" rows="4" placeholder="Tu mensaje" required></textarea>
                </div>
        
                <!-- Submit Button -->
                <button type="submit" class="btn btn-primary">Enviar</button>
            </form>
        </div>
    </div>
</div>

{% endblock %}

pagina/templates/paginas/factura.html
{% extends "base.html" %}

{% block titulo %} Factura {% endblock %}

{% block contenido %} 

<div class="container mt-5">
    <h2>Factura</h2>
    <div class="table-responsive">
        <table class="table table-striped table-bordered">
            <thead>
              <tr>
                <th style="width: 25%">Nombre</th>
                <th style="width: 25%">Precio Unitario</th>
                <th style="width: 15%">Cantidad</th>
                <th>Total</th>
              </tr>
            </thead>
            <tbody>
            {% for cart_material in cart_material %}
              <tr>
                <td>{{ cart_material.material.nombre }}</td>
                <td>${{ cart_material.material.precio }}</td>
                <td>
                    <div class="row">
                        <div class="col-sm">
                            <form method="post" action="{% url 'remove_from_budget' cart_material.material.id %}">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-outline-danger">-</button>
                            </form>
                        </div>
                        <div class="col-sm text-center">
                            {{ cart_material.quantity }}
                        </div>
                        <div class="col-sm">
                            <form method="post" action="{% url 'add_to_budget_factura' cart_material.material.id %}">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-outline-success">+</button>
                            </form>
                        </div>
                      </div>
                </td>
                <td>${% widthratio cart_material.material.precio 1 cart_material.quantity %}</td>
              </tr>
            {% endfor %}
              <!-- Add more rows as needed -->
            </tbody>
        </table>
    </div>
    <div class="text-end">
        <h2>Total: ${{ total }}</h2>
    </div>
</div>

{% endblock %}

pagina/templates/paginas/index.html
{% extends "base.html" %}

{% block titulo %} Inicio {% endblock %}

{% block contenido %} 

<div
  class="bg-image p-5 text-center shadow-1-strong mb-5 text-white"
  style="background-image: url('https://mdbcdn.b-cdn.net/img/new/slides/003.webp');"
>
  <h1 class="mb-3 h2"><strong>Misión y Visión</strong></h1>

  <div class="p-5">
  <p><strong>Nuestra Misión</strong></p>
  <p>
    Nuestra misión es superar las expectativas de nuestros clientes mediante la entrega de proyectos de construcción de alta calidad, en tiempo y dentro del presupuesto acordado. 
  <br>
    Nos esforzamos por establecer relaciones sólidas y duraderas con nuestros clientes, basadas en la confianza, la transparencia y la integridad. 
  <br>
    Buscamos contribuir al desarrollo sostenible de las comunidades en las que operamos, generando empleo local y promoviendo prácticas constructivas respetuosas con el medio ambiente.
  </p>
  </div>

  <div class="p-5">
    <p><strong>Nuestra Visión</strong></p>
    <p>
        Aspiramos a ser reconocidos como líderes en el sector de la construcción, destacándonos por nuestra excelencia en la ejecución de proyectos y nuestra capacidad para adaptarnos a las últimas innovaciones y tecnologías en la industria.
    <br>
        Buscamos ser la elección preferida de los clientes que valoran la calidad, la confiabilidad y el compromiso en cada etapa del proceso constructivo.
    <br>
        Además, visualizamos un crecimiento sostenible que nos permita expandir nuestras operaciones y contribuir de manera significativa al desarrollo de nuevas comunidades.
    </div>


</div>
<div class="container mt-5 mb-5">
    <div class="row">
        <div class="col-lg-6 text-center">
            <h2><strong>NUESTROS OBJETIVOS</strong></h2>
            <img src="/img/img/herramientas.png" class="img-fluid" alt="Placeholder">
        </div>
        <div class="col-lg-6 d-flex align-items-center">
            Garantizar la satisfacción total del cliente, cumpliendo con los más altos estándares de calidad en cada proyecto.
            <br>
            Mejorar continuamente nuestros procesos y adoptar tecnologías innovadoras para aumentar la eficiencia y reducir costos.
            <br>
            Fomentar un ambiente de trabajo seguro y saludable para nuestro equipo, promoviendo la capacitación constante y el desarrollo profesional.
            <br>
            Contribuir al desarrollo sostenible mediante prácticas constructivas respetuosas con el medio ambiente y la comunidad.
            <br>
            Expandir nuestra presencia en el mercado, identificando oportunidades de crecimiento y diversificación de servicios.
        </div>
    </div>
</div>

{% endblock %}

pagina/templates/paginas/nosotros.html
{% extends "base.html" %}

{% block titulo %} Nosotros {% endblock %}

{% block contenido %} 

<div class="container mt-5 mb-5 p-5">
    <div class="row">
        <div class="col-lg-6">
            <h2>Nosotros</h2>
            <p>
                Somos una pequeña empresa constructora comprometida con la excelencia en la ejecución de proyectos de construcción. 
            </p>
            <p>
                Nos enorgullece contar con un equipo altamente calificado y apasionado por la construcción, respaldado por años de experiencia en el sector. 
            </p>
            <p>
                Nos destacamos por nuestra dedicación a la calidad, la eficiencia y la satisfacción del cliente en cada proyecto que emprendemos.
            </p>
        </div>
        <div class="col-lg-6">
            <img src="/img/img/obrero.jpg" class="img-fluid" alt="Placeholder">
        </div>
    </div>
</div>

{% endblock %}

pagina/templates/paginas/presupuesto.html
{% extends "base.html" %}

{% block titulo %} Presupuesto {% endblock %}

{% block contenido %} 

<div class="container mt-5">
  <div class="card-body">
    <h4 class="card-title text-center">¡Seleccione los materiales para su presupuesto!</h4>
    <div class="container mt-4 mb-3">
      <div class="row">
        <div class="col-lg-9">
        
      <div class="row justify-content-center">
        {% for material in material %}
        <div class="card m-1 text-center" style="width: 18rem;">
          {% if material.imagen %}
          <img class="card-img-top" src="{{ material.imagen.url }}"> 
          {% endif %}
          <div class="card-body">
            <h5 class="card-title">{{ material.nombre }}</h5>
            <p class="card-text">{{ material.get_medida_display }}</p>
            <p class="card-text">${{ material.precio }}</p>
            <div class="row">
              <div class="col-sm">
                <form action="{% url 'add_to_budget' material.id %}" method="post">
                  {% csrf_token %}
                  <button class="btn btn-primary" type="submit">+</button>
                </form>
              </div>         
              <div class="col-sm">
                <form action="{% url 'remove_from_budget_presupuesto' material.id %}" method="post">
                  {% csrf_token %}
                  <button class="btn btn-primary" type="submit">-</button>
                </form>             
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>

        </div>

      <div class="col">
      <ol class="list-group list-group-numbered" style="width: 18rem;">
        {% for cart_material in cart_material %}
        <li class="list-group-item d-flex justify-content-between align-items-start">
          <div class="ms-2 me-auto">
            <div class="fw-bold"> {{ cart_material.material.nombre }}</div>
            {{ cart_material.material.precio }}
          </div>
          <span class="badge bg-primary rounded-pill">{{ cart_material.quantity }}</span>
        </li>
        {% endfor %}
        <a name="" id="" class="btn btn-info" href="{% url 'factura' %}" role="button">Siguiente</a>
      </ol>
    </div>

    </div>
  </div>
</div>

{% endblock %}

pagina/templates/paginas/servicios.html
{% extends "base.html" %}

{% block titulo %} Servicios {% endblock %}

{% block contenido %} 

<div class="container mt-5 text-center">
   <h1>Servicios</h1>
   <div class="row">
    <div class="col-lg-4 col-md-6">
        <div class="card border-0">
            <img src="/img/img/budget.jpg" class="card-img-top" alt="Card 1" width="50" height="100">
            <div class="card-body">
                <h5 class="card-title">Presupuesto</h5>
                <p class="card-text">This is the content of Card 1.</p>
                <a href="{% url 'presupuesto' %}" class="btn btn-primary stretched-link">Go somewhere</a>
            </div>
        </div>
    </div>
    <div class="col-lg-4 col-md-6">
        <div class="card border-0">
            <img src="card-image-2.jpg" class="card-img-top" alt="Card 2">
            <div class="card-body">
                <h5 class="card-title">Consultoría</h5>
                <p class="card-text">This is the content of Card 2.</p>
            </div>
        </div>
    </div>
    <div class="col-lg-4 col-md-6">
        <div class="card border-0">
            <img src="card-image-3.jpg" class="card-img-top" alt="Card 3">
            <div class="card-body">
                <h5 class="card-title">Servicio 3</h5>
                <p class="card-text">Servicio 3</p>
            </div>
        </div>
    </div>
</div>
</div>

{% endblock %}